/**
 * Game Constants
 * Centralized configuration for all game mechanics
 */

// ============================================================================
// TIME & DAY SETTINGS
// ============================================================================

/** Duration of a game day in milliseconds */
export const DAY_DURATION_MS = 5000

/** Number of days in a game year */
export const DAYS_PER_YEAR = 365

/** Daily operational cost deducted each day */
export const DAILY_OPERATIONAL_COST = 10

// ============================================================================
// CUSTOMER & ORDER SETTINGS
// ============================================================================

/** Cost to launch a promotion campaign */
export const PROMOTION_COST = 500

/** Minimum number of customers generated by promotion */
export const MIN_CUSTOMERS_PER_PROMOTION = 2

/** Maximum number of customers generated by promotion */
export const MAX_CUSTOMERS_PER_PROMOTION = 5

/** Minimum number of orders per customer */
export const MIN_ORDERS_PER_CUSTOMER = 1

/** Maximum number of orders per customer */
export const MAX_ORDERS_PER_CUSTOMER = 4

// ============================================================================
// WORKER SETTINGS
// ============================================================================

/** Cost to post a job offer */
export const JOB_OFFER_COST = 500

/** Minimum number of workers generated by job offer */
export const MIN_WORKERS_PER_OFFER = 3

/** Maximum number of workers generated by job offer */
export const MAX_WORKERS_PER_OFFER = 6

/** Minimum contract duration in months */
export const MIN_CONTRACT_DURATION_MONTHS = 1

/** Maximum contract duration in months */
export const MAX_CONTRACT_DURATION_MONTHS = 12

/** Multiplier for upgrade price calculation */
export const WORKER_UPGRADE_PRICE_MULTIPLIER = 1.5

/** Productivity increase per level upgrade */
export const WORKER_PRODUCTIVITY_INCREASE = 1.2

/** Default days per month for contract calculation */
export const DAYS_PER_MONTH = 30

// ============================================================================
// BAKING SETTINGS
// ============================================================================

/** Default progress increment per click */
export const DEFAULT_BAKING_PROGRESS_INCREMENT = 10

/** Progress threshold to complete a baking cycle */
export const BAKING_PROGRESS_THRESHOLD = 100

// ============================================================================
// INDUSTRY LEVELS
// ============================================================================

export interface IndustryLevelConfig {
  level: number
  maxWorkers: number
  upgradePrice: number
  name: string
}

export const INDUSTRY_LEVELS: IndustryLevelConfig[] = [
  { level: 1, maxWorkers: 10, upgradePrice: 0, name: 'Home Kitchen' },
  {
    level: 2,
    maxWorkers: 20,
    upgradePrice: 200000,
    name: 'Neighborhood Bakery',
  },
  { level: 3, maxWorkers: 40, upgradePrice: 500000, name: 'City Chain' },
  { level: 4, maxWorkers: 80, upgradePrice: 1000000, name: 'Regional Empire' },
  { level: 5, maxWorkers: 150, upgradePrice: 20000000, name: 'Global Brand' },
]

/** Maximum industry level */
export const MAX_INDUSTRY_LEVEL = INDUSTRY_LEVELS.length

// ============================================================================
// INITIAL GAME STATE
// ============================================================================

/** Starting money for new games */
export const INITIAL_MONEY = 30000

/** Starting day */
export const INITIAL_DAY = 1

/** Starting year */
export const INITIAL_YEAR = 1

/** Starting oven level */
export const INITIAL_OVEN_LEVEL = 1

// ============================================================================
// WORKER GENERATION RANGES
// ============================================================================

export const WORKER_PRODUCTIVITY_RANGE = {
  min: 1.0,
  max: 5.0,
} as const

export const WORKER_PRICE_RANGE = {
  min: 100,
  max: 1500,
} as const

// ============================================================================
// MONEY FORMATTING
// ============================================================================

export const MONEY_FORMAT_CONFIG = {
  style: 'currency' as const,
  currency: 'USD',
  minimumFractionDigits: 0,
  maximumFractionDigits: 0,
}
