export const JOB_OFFER_COST = 500
export const MIN_WORKERS_PER_OFFER = 3
export const MAX_WORKERS_PER_OFFER = 6
export const MIN_CONTRACT_DURATION_MONTHS = 1
export const MAX_CONTRACT_DURATION_MONTHS = 12
export const WORKER_UPGRADE_PRICE_MULTIPLIER = 2.5
export const WORKER_PRODUCTIVITY_INCREASE = 1.2
export const DAYS_PER_MONTH = 30
